# Use postgres/example user/password credentials
version: '3.9'

services:
  flask:
    build: .
    image: ananazzz/flask-image:latest
    container_name: flask-container
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - 8081:5000
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    restart: always
    container_name: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 111111

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080