DROP TABLE IF EXISTS userWithAchievements;
DROP TABLE IF EXISTS achievement;
DROP TABLE IF EXISTS user_progress_in_module;
DROP TABLE IF EXISTS page;
DROP TABLE IF EXISTS "module";
DROP TABLE IF EXISTS knowledge;
DROP TABLE IF EXISTS track;
DROP TABLE IF EXISTS AppUser;

CREATE TABLE AppUser (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	last_name TEXT NOT NULL,
	password TEXT NOT NULL,
    progress INTEGER NOT NULL
);

CREATE TABLE track (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
    quantityModules INTEGER
);

CREATE TABLE knowledge (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	content TEXT
);

CREATE TABLE "module" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    quantityPage INTEGER NOT NULL,
    quantityCoin INTEGER NOT NULL,
    startContent TEXT NOT NULL,
    endContent TEXT NOT NULL,
    numberInTrack INTEGER NOT NULL,
    idTrack INTEGER NOT NULL REFERENCES track(id),
    UNIQUE(numberInTrack,idTrack)
);

CREATE TABLE page (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    name TEXT NOT NULL,
    numberInModule INTEGER NOT NULL,
    idModule INTEGER NOT NULL REFERENCES "module"(id),
    UNIQUE (idModule,numberInModule)
);

CREATE TABLE user_progress_in_module (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	numberLastCompletePage INTEGER NOT NULL,
	allQuantityPage INTEGER NOT NULL,
	id_user INTEGER NOT NULL REFERENCES AppUser(id),
	id_module INTEGER NOT NULL REFERENCES "module"(id)
);

CREATE TABLE achievement(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    picture TEXT NOT NULL
);

CREATE TABLE userWithAchievements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user INTEGER NOT NULL REFERENCES AppUser(id),
    id_achievements INTEGER NOT NULL REFERENCES achievement(id)
);

INSERT INTO AppUser (name, last_name, password, progress) VALUES ('Alice', 'Smith', 'pass123', 30);
INSERT INTO AppUser (name, last_name, password, progress) VALUES ('Bob', 'Johnson', 'qwerty', 50);
INSERT INTO AppUser (name, last_name, password, progress) VALUES ('Charlie', 'Brown', 'abc123', 70);

INSERT INTO track (name, quantityModules) VALUES ('Web Development', 8);
INSERT INTO track (name, quantityModules) VALUES ('Data Science', 6);
INSERT INTO track (name, quantityModules) VALUES ('Mobile App Development', 5);

INSERT INTO knowledge (name, content) VALUES ('Machine Learning', 'Introduction to machine learning algorithms');
INSERT INTO knowledge (name, content) VALUES ('SQL Basics', 'Fundamentals of relational databases and SQL queries');
INSERT INTO knowledge (name, content) VALUES ('JavaScript Essentials', 'Basics of JavaScript programming language');

INSERT INTO "module" (name, quantityPage, quantityCoin, startContent, endContent, numberInTrack, idTrack) VALUES ('Module 1', 12, 100, 'Module 1 Start', 'Module 1 End', 1, 1);
INSERT INTO "module" (name, quantityPage, quantityCoin, startContent, endContent, numberInTrack, idTrack) VALUES ('Module 2', 10, 150, 'Module 2 Start', 'Module 2 End', 2, 1);
INSERT INTO "module" (name, quantityPage, quantityCoin, startContent, endContent, numberInTrack, idTrack) VALUES ('Module 1', 15, 120, 'Module 1 Start', 'Module 1 End', 1, 2);

INSERT INTO page (content, name, numberInModule, idModule) VALUES ('Page 1 Content', 'Page 1', 1, 1);
INSERT INTO page (content, name, numberInModule, idModule) VALUES ('Page 2 Content', 'Page 2', 2, 1);
INSERT INTO page (content, name, numberInModule, idModule) VALUES ('Page 1 Content', 'Page 1', 1, 2);

INSERT INTO user_progress_in_module (numberLastCompletePage, allQuantityPage, id_user, id_module) VALUES (5, 12, 1, 1);
INSERT INTO user_progress_in_module (numberLastCompletePage, allQuantityPage, id_user, id_module) VALUES (7, 10, 2, 2);
INSERT INTO user_progress_in_module (numberLastCompletePage, allQuantityPage, id_user, id_module) VALUES (3, 15, 3, 1);

INSERT INTO achievement (name, description, picture) VALUES ('First Achievement', 'Description of First Achievement', 'achievement1.jpg');
INSERT INTO achievement (name, description, picture) VALUES ('Data Science Master', 'Complete all data science modules', 'achievement2.jpg');
INSERT INTO achievement (name, description, picture) VALUES ('Web Development Expert', 'Master web development skills', 'achievement3.jpg');

INSERT INTO userWithAchievements (id_user, id_achievements) VALUES (1, 1);
INSERT INTO userWithAchievements (id_user, id_achievements) VALUES (2, 2);
INSERT INTO userWithAchievements (id_user, id_achievements) VALUES (3, 3);



